import te from 'date-fns/esm/locale/te/index.js';
import { StyleSheet } from 'react-native';
import theme from '../../constants/theme';

const styles = StyleSheet.create({
    container: {
        backgroundColor: theme.colors.white,
        height: 144,
        width: 348,
        borderRadius: 16,
        marginTop: 13,
    },
    touchCard: {
        backgroundColor: theme.colors.white,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        height: 144,
        width: 348,
    },
    containerImgTex: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        alignContent: 'center',
        marginTop: -56,
        marginLeft: -16,
        marginRight: 98,
    },
    containerImg: {
        backgroundColor: '#15357A',
        width: 50,
        height: 50,
        borderRadius: 8,
        marginLeft: -40,
    },
    touchLocation: {
        display: 'flex',
        justifyContent: 'center',
        alignContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top: 92,
        flexDirection: 'row',
        left: 16,
    },
    textLocation: {
        fontStyle: 'normal',
        fontWeight: '400',
        fontSize: 14,
        lineHeight: 17,
        color: '#15357A',
    },
    img: {
        marginTop: 'auto',
        marginLeft: 'auto',
        marginBottom: 'auto',
        marginRight: 'auto',
    },
    title: {
        fontWeight: '600',
        fontSize: 16,
        lineHeight: 19,
        color: '#15357A',
    },
    date: {
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 15,
        fontStyle: 'normal',
        color: '#15357A',
    },
    detail: {
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 15,
        fontStyle: 'normal',
        color: '#15357A',
    },
    touchCheckIn: {
        backgroundColor: theme.colors.blue,
        position: 'absolute',
        marginLeft: 226,
        marginRight: 16,
        marginTop: 95,
        marginBottom: 66,
        borderRadius: 8,
        width: 106,
        height: 33,
        alignItems: 'center',
    },
    textCheckIn: {
        textAlign: 'center',
        color: theme.colors.white,
        marginTop: 7,
        marginBottom: 7,
        marginLeft: 11,
        marginRight: 11,
        fontWeight: '600',
        fontSize: 16,
        lineHeight: 19,
    },
    touchPlus: {
        position: 'absolute',
        marginLeft: 292,
        marginTop: 17,
        marginBottom: 111,
    },
});
export default styles;
